CREATE DATABASE BluePrint
GO
USE BluePrint
GO
CREATE TABLE TipoClientes(
	ID SMALLINT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(30) NOT NULL
)
GO
CREATE TABLE Clientes(
	ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TipoCliente SMALLINT NOT NULL FOREIGN KEY REFERENCES TipoClientes(ID),
	RazonSocial VARCHAR(50) NOT NULL UNIQUE,
	Cuit VARCHAR(10) NOT NULL UNIQUE,
	Mail VARCHAR(100) NULL,
	Telefono VARCHAR(15) NULL,
	Celular VARCHAR(15) NULL,
)
GO
CREATE TABLE Proyectos(
	ID SMALLINT NOT NULL PRIMARY KEY IDENTITY (1,1),
	IDCliente SMALLINT NOT NULL FOREIGN KEY REFERENCES Clientes(ID),
	Nombre VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(512) NULL,
	FechaInicio DATE NOT NULL,
	FechaFin DATE NOT NULL,
	Costo MONEY NOT NULL,
	Estado BIT NOT NULL DEFAULT(1),
)
