/*
	UNA EMPRESA NECESITA ALMACENAR INFORMACION DE LAS PERSONAS QUE INGRESAN
	A VISITAR SU ESTABLECIMIENTO.
*/

CREATE DATABASE Empresa
GO
USE Empresa
GO
CREATE TABLE VISITANTES(
	dni varchar(8) NOT NULL PRIMARY KEY,
	nombre varchar(30) NOT NULL,
	apellido varchar(30) NOT NULL
)
GO
CREATE TABLE DETALLES(
	dni varchar(8) NOT NULL PRIMARY KEY REFERENCES VISITANTES(dni),
	fecha_nacimiento DATE NOT NULL CHECK(fecha_nacimiento < GETDATE()),
	nacionalidad varchar(30) NOT NULL,
	genero char NOT NULL
)