USE BluePrint
GO
CREATE TABLE Modulos(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDProyecto VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES Proyectos(ID),
	Nombre VARCHAR(50) NOT NULL,
	Descripcion VARCHAR(512) NULL,
	HorasEstimadas SMALLINT NOT NULL CHECK(HorasEstimadas > 0),
	Costo MONEY NOT NULL CHECK(Costo > 0),
	FechaInicio DATE NOT NULL,
	FechaEstimadaFin DATE NOT NULL,
	FechaFin DATE NOT NULL,
	CONSTRAINT CHK_FechaEstimadaFin CHECK(FechaEstimadaFin >= FechaInicio),
	CONSTRAINT CHK_FechaFin CHECK(FechaFin >= FechaInicio)
)
GO
CREATE TABLE Paises(
	ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL
)
GO
CREATE TABLE Ciudades(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL,
	IDPais SMALLINT NOT NULL FOREIGN KEY REFERENCES Paises(ID)
)
GO
CREATE TABLE Colaboradores(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	Apellidos VARCHAR (50) NOT NULL,
	Genero CHAR(1) NULL CHECK(Genero IN('M','F')),
	Email VARCHAR(100) NULL,
	Celular VARCHAR(50) NULL,
	Domicilio VARCHAR(250) NULL,
	Tipo CHAR(1) NOT NULL CHECK(Tipo = 'I' OR Tipo = 'E'),
	FechaNacimiento DATE NOT NULL CHECK(FechaNacimiento < GETDATE()),
	IDCiudad INT NULL FOREIGN KEY REFERENCES Ciudades(ID),
	CONSTRAINT CHK_EmailCelular CHECK(Email IS NOT NULL OR Celular IS NOT NULL)
)